Repository Uol-Project-Collab/UOL_grades_calculator, pull requests merged in 2025-04, with the labels that each got.

#1 UGC-13 Design home page basic layout
  frontend/css/styles.css
  frontend/index.html
Labels: enhancement, jira task

#2 docs: Updated Readme
  README.md
Labels: documentation, question

#6 UGC-18 Add module functionality (frontend)
  frontend/css/styles.css
  frontend/index.html
  frontend/js/script.js
Labels: enhancement, good first issue, jira task

#10 UGC-23 Read module functionality (frontend)
  frontend/css/styles.css
  frontend/index.html
  frontend/js/script.js
Labels: enhancement, jira task

#14 OOP Overhaul
  frontend/index.html
  frontend/js/app.js
  frontend/js/core/FormManager.js
  frontend/js/core/ModuleManager.js
  frontend/js/data/modulesByLevel.js
  frontend/js/script.js
  frontend/js/services/MessageService.js
  frontend/js/services/StorageService.js
Labels: enhancement, help wanted, good first issue

#15 UGC-15/21/26/55 all completed, tested and ready to merge with main
  backend/.firebaserc
  backend/.gitignore
  backend/config/firebase.js
  backend/controllers/moduleController.js
  backend/firebase.json
  backend/firestore.indexes.json
  backend/firestore.rules
  backend/index.js
  backend/middlewares/errorHandler.js
  backend/models/module.js
  backend/package-lock.json
  backend/package.json
  backend/routes/moduleRoutes.js
Labels: jira task

#16 Avg grade functionality
  backend/controllers/avgGradeController.js
  backend/index.js
  backend/routes/avgGradesRoutes.js
Labels: jira task

#19 UGC-57 Use endpoint to retrieve and show all modules in the form (frontend)
  .vscode/settings.json
  frontend/index.html
  frontend/js/app.js
  frontend/js/core/FormManager.js
  frontend/js/data/modulesByLevel.js
Labels: jira task

#20 UGC-33 Edit module functionality (backend)
  backend/controllers/moduleController.js
  backend/models/module.js
  backend/package-lock.json
  backend/package.json
  backend/routes/moduleRoutes.js
  backend/validators/moduleValidator.js
Labels: jira task

#22 Enhanced add module to add multiple modules at once
  backend/controllers/moduleController.js
  backend/routes/moduleRoutes.js
Labels: enhancement

#25 UGC-58 Use endpoints to add modules to "test" student and to show them in the dashboard (frontend)
  backend/controllers/moduleController.js
  frontend/css/styles.css
  frontend/index.html
  frontend/js/app.js
  frontend/js/core/FormManager.js
  frontend/js/core/ModuleManager.js
  frontend/js/data/ModuleFetcher.js
  frontend/js/data/modulesByLevel.js
  frontend/js/services/StorageService.js
Labels: jira task

#27 UGC-40 Grade calculation feature (frontend)
  frontend/css/styles.css
  frontend/index.html
  frontend/js/app.js
  frontend/js/core/FormManager.js
  frontend/js/core/ModuleManager.js
  frontend/js/data/AverageGrade.js
  frontend/js/data/ModuleFetcher.js
Labels: jira task

#29 UGC 47: Download/Save as PDF feature (frontend)
  frontend/index.html
  frontend/js/app.js
  frontend/js/core/FormManager.js
  frontend/js/core/ModuleManager.js
  frontend/js/data/AverageGrade.js
  frontend/js/data/ModuleFetcher.js
  frontend/js/services/MessageService.js
Labels: enhancement, jira task

#32 User creation and authentication completed, error handling modified
  backend/config/firebase.js
  backend/controllers/avgGradeController.js
  backend/controllers/moduleController.js
  backend/firebase.client.js
  backend/firestore.indexes.json
  backend/firestore.rules
  backend/index.js
  backend/middlewares/authMiddleware.js
  backend/middlewares/errorHandler.js
  backend/models/module.js
  backend/package-lock.json
  backend/package.json
  backend/routes/authRoutes.js
  backend/routes/avgGradesRoutes.js
  backend/routes/moduleRoutes.js
  backend/services/authService.js
  backend/utils/catchAsync.js
  backend/validators/moduleValidator.js
  backend/validators/userValidator.js
Labels: enhancement, jira task
